### ISSUE TITLE
请把工程打包放到pypi上把

### ISSUE THREAD

**Issue by huanghao** [QcloudApi/qcloudapi-sdk-python#12]
要不然没法用pip安装。只能自己来打包。谢谢

**Comment by QcloudApi** [comment]
已经部署到pypi上了，第一个版本是https://pypi.python.org/pypi/qcloudapi-sdk-python/2.0.0，最新的版本是https://pypi.python.org/pypi/qcloudapi-sdk-python/2.0.8
