### ISSUE TITLE
如何遍历一个账号下面的所有region的相关资源

### ISSUE THREAD

**Issue by mesopodamia** [QcloudApi/qcloudapi-sdk-python#16]
我现在一个账号下面有很多项目，每个项目又有多个region申请了服务，请问如何遍历获取每个项目的每个region的服务资源信息？

**Comment by QcloudApi** [comment]
这得您根据自己的需要用sdk来编程了，把每个项目的secretId和scretKey作为一层循环，把每个region作为下一层循环，依次调用相关资源的查询接口。
查询region列表的api：https://cloud.tencent.com/document/product/213/9456
