### ISSUE TITLE
README.md 例子中的错误

### ISSUE THREAD

**Issue by hzlpy** [QcloudApi/qcloudapi-sdk-python#19]
[例子](https://github.com/QcloudApi/qcloudapi-sdk-python/blob/master/README.md#例子)
```
# 重新设置请求的SignatureMethod
SignatureMethod = 'HmacSHA256'
service.setRequestMethod(SignatureMethod)
```
这里的 `setRequestMethod` 应该为 `setSignatureMethod` 吧？

**Comment by miaozaiye** [comment]
是的，这个问题我也碰到了想提。

**Comment by QcloudApi** [comment]
fixed in c43541f
