### ISSUE TITLE
调用 qcloudapi-sdk-python 的 DescribeInstances 返回结果中没有 InstanceType字段

### ISSUE THREAD

**Issue by bonfy** [QcloudApi/qcloudapi-sdk-python#25]
查询Instance实例状态

[API文档](https://cloud.tencent.com/document/product/213/9388) 里面返回结果是有 InstanceType字段的，为什么调用 qcloudapi-sdk-python 以及 `qcloudcli cvm DescribeInstances`是没有InstanceType字段的，怎么从 CPU 和 Memory 知道这个InstanceType啊？

 API文档里面的返回结果：
{
    "Response": {
        "TotalCount": 2,
        "InstanceSet": [
            {
                "Placement": {
                    "Zone": "ap-guangzhou-1",
                    "HostId": "",
                    "ProjectId": 0
                },
                "InstanceId": "ins-r8hr2upy",
                "InstanceType": "S1.SMALL2",
                "CPU": 1,
                "Memory": 2,
                "InstanceName": "\u6d4b\u8bd5\u5b9e\u4f8b",
                "InstanceChargeType": "PREPAID",
                "SystemDisk": {
                    "DiskType": "CLOUD_BASIC",
                    "DiskId": "disk-4rnslbwq",
                    "DiskSize": 20
                },
                "DataDisks": [
                    {
                        "DiskType": "CLOUD_BASIC",
                        "DiskId": "disk-4rnslb35",
                        "DiskSize": 50
                    }
                ],
                "PrivateIpAddresses": [
                    "10.104.37.58"
                ],
                "PublicIpAddresses": [
                    "123.207.32.83"
                ],
                "InternetAccessible": {
                    "InternetMaxBandwidthOut": 2,
                    "InternetChargeType": "BANDWIDTH_PREPAID",
                    "PublicIpAssigned": "TRUE"
                },
                "VirtualPrivateCloud": {
                    "VpcId": "vpc-4e78ea76",
                    "SubnetId": "subnet-6d7kj98i",
                    "AsVpcGateway": "TRUE"
                },
                "ImageId": "img-0vbqvzfn",
                "RenewFlag": "NOTIFY_AND_AUTO_RENEW",
                "CreatedTime": "2016-12-02T00:22:40Z",
                "ExpiredTime": "2017-01-02T00:22:48Z"
            }
        ],
        "RequestId": "6EF60BEC-0242-43AF-BB20-270359FB54A7"
    }
}

**Comment by QcloudApi** [comment]
文档中说明了要传一个Version字段

Version | String | 是 | 表示API版本号，主要用于标识请求的不同API版本。 本接口第一版本可传：2017-03-12。
-- | -- | -- | --

对于sdk，参考https://github.com/QcloudApi/qcloudapi-sdk-python/blob/30916effee3f87d59f4c6ab61ad9ca2c638acb94/tests/demo.py#L37

对于cli，参考https://github.com/QcloudApi/qcloudcli/tree/5addbb273e4743fedc5ea963fbd78575259d9ee7#指定api版本

**Comment by bonfy** [comment]
@QcloudApi  那请问 我在信版本的接口中 如何获取到 InstanceType 呢？

**Comment by QcloudApi** [comment]
sdk现在的实现还不是很友好，service.call返回的是裸的服务器消息体，你可以这样做

```
    r = service.call(action, action_params)
    for ins in json.loads(r.decode())['Response']['InstanceSet']:
        print(ins['InstanceType'])
```

如果是cli，你可以这样做

```
$ qcloudcli cvm DescribeInstances --filter Response.InstanceSet[*].InstanceType
```

**Comment by QcloudApi** [comment]
cli这种做法在文档中已经描述了，更多用法请阅读文档，如文档不清晰请在qcloudcli项目中提出issue

**Comment by bonfy** [comment]
@QcloudApi  非常感谢你的耐心解答

可能是我的问题描述的不清楚，关于你上面的解答，我明白，都是基于 设置了 Version = 2017-03-12 的返回结果，你这样的写法没有问题，也是能得到答案的

当然我也全部看过你们的文档，也看过你们 sdk-python 的代码，这个代码就是拼一个http的url，然后 call一下，当然里面就实现了个产生 Signature 和 Timestamp

那么我说下我现在的问题，当然这个问题我在你们API页面上也反馈了，可能不属于 python-sdk的范畴，但是我觉得我是遇到了这样的问题

打个比方我需要的信息是：

{
            "instanceId": "qcvmfd57f3113bc6fd6f0c8ce381f5433539",
            "unInstanceId": "ins-gsbuwc26",
            "unImgId": "img-0vbqvzfn",
            "InstanceType": "S2.2XLARGE32",
}

首先 我现在 新版的API 和 旧版的API 调用两次，是能获得我所有要的信息的

这个光调用新版的 我取不到 InstanceType, 而调用 旧版的 “ 2017-03-12” 又拿不到  InstanceId，旧版的 instanceId 是新版的 unInstanceId, 我的意思是 你们API的团队为啥不一起把  InstanceType 返回到  json里面去呢？ 而且如果以后就版本停用后，我根本没有一个接口可以查询到某个 instanceId 它对应的 InstanceType。光返回个 Mem 和 CPU 叫我如何确定它的 InstanceType啊？

所以现在我的问题暂时是能解决的，要调用两遍接口 新版的取到其它的信息，然后必须再调用一遍旧版的才能拿到InstanceType信息。（而且你们返回的 limit是不能大于100的，所以我有超过 100台instance还要调好几遍接口。。。） 

我的想法也很简单，当然这不是你们 python-sdk 的责任，为啥 新版API返回的时候 不把InstanceType一起返回了啊，数据库肯定有，但为啥不返回，实在想不通，这很折腾用户好么。我也实在想不到其它渠道反馈了，就在这里吐吐槽。

希望能在新版本里面把 InstanceType 加入返回结果集，谢谢。

**Comment by bonfy** [comment]
现在的问题是 新版本 返回的是 mem 和 cpu 字段，通过这两个字段我是不能知道 InstanceType的，但是如果多返回给我一个 InstanceType,即使 mem 和  cpu 不告诉我，我也能通过[实例配置表](https://cloud.tencent.com/document/product/213/2177#S3) 知道这个Instance的 mem 和 cpu，所以设计这个API返回值的时候 是不是 把 InstanceType加进去更妥当些

**Comment by QcloudApi** [comment]
你好像搞混了。

目前默认使用旧版的，即不指定Version，返回的数据里是没有InstanceType的。如果指定了Version=2017-03-12，意味着使用的是新版的，返回的数据里是有InstanceType的。

之所以不默认使用Version=2017-03-12的新版API，是因为只有cvm支持了，大多数服务尚未支持。

对于你想获取的字段信息，旧版API，即不传Version，目前unImgId可能为空。新版API，即传Version=2017-03-12，instanceId是获取不到的，InstanceId字段是有的，和旧版的unInstanceId一致。如果出于某种原因，你一定要获取instanceId，即qcvmf4b542ad7b4cd49f2db57a733368d5b1这种格式的，那也只能访问旧版API了。

新版，即Version=2017-03-12并不仅仅是对旧版的升级，它是全新设计开发的，和旧版不兼容的，因此调了版本号，并不是折腾用户，而是以前的设计无法支持更多更好的功能，迫不得已才升级。用户使用新版的API，即传递Version-2017-03-12，其实是获得了相比使用旧版，即不传Version时更多的能力。改变的过程中引起的不便，请谅解

在API页面反馈只是反馈给了文档团队，如果你对产品本身有投诉、意见、建议、需求、缺陷需要反馈，请登录后访问工单系统：https://console.cloud.tencent.com/workorder/category

**Comment by bonfy** [comment]
@QcloudApi 不好意思，是我搞错了，先入为主了， 我以为文档上面的 红字旧文档 是跳转到旧文档的链接...

谢谢你的耐心解答，非常感谢
