### ISSUE TITLE
Wenzhi module doesn't exist

### ISSUE THREAD

**Issue by yanxiangyi** [QcloudApi/qcloudapi-sdk-python#28]
`from QcloudApi.qcloudapi import QcloudApi

module = 'wenzhi.api.qcloud.com'
action = 'TextSentiment'

config = {
    'Region': 'gz',
    'secretId': 'abcd',
    'secretKey': 'abcd',
    'method': 'GET',
    'SignatureMethod': 'HmacSHA256'
}

action_params = {
    'content':'李亚鹏挺王菲：加油！孩儿他娘。',
}

try:
    service = QcloudApi(module, config)
    secretId = 'abcd'
    service.setSecretId(secretId)
    secretKey = 'abcd'
    service.setSecretKey(secretKey)
    region = 'gz'
    service.setRegion(region)
    method = 'GET'
    service.setRequestMethod(method)
    SignatureMethod = 'HmacSHA256'
    service.setSignatureMethod(SignatureMethod)
    print(service.generateUrl(action, action_params))
    print(service.call(action, action_params))
except Exception as e:
    import traceback
    print('traceback.format_exc():\n%s' % traceback.format_exc())`

traceback.format_exc():
Traceback (most recent call last):
  File "<ipython-input-1-8a3c6fe5327e>", line 48, in <module>
    print(service.generateUrl(action, action_params))
  File "/usr/local/lib/python3.4/dist-packages/QcloudApi/qcloudapi.py", line 143, in generateUrl
    service = self._factory(self.module, self.config)
  File "/usr/local/lib/python3.4/dist-packages/QcloudApi/qcloudapi.py", line 123, in _factory
    raise ValueError('module not exists')
ValueError: module not exists

**Comment by QcloudApi** [comment]
from: module = 'wenzhi.api.qcloud.com'
to: module = 'wenzhi'

wenzhi doens't support HmacSHA256, use HmacSHA1
