### ISSUE TITLE
签名计算问题

### ISSUE THREAD

**Issue by newlightdd** [QcloudApi/qcloudapi-sdk-python#3]
计算签名里面的一句中
        srcStr = method.upper() + requestHost + requestUri + '?' + "&".join(k.replace("_",".") + "=" + str(list[k]) for k in sorted(list.keys()))

为什么要把"_" 替换成 "."?

**Comment by QcloudApi** [comment]
php框架历史遗留问题，有兴趣可以参见https://stackoverflow.com/questions/3742653/why-strings-in-post-can-not-contain-a-dot
