### ISSUE TITLE
Missing cmq module

### ISSUE THREAD

**Issue by baikai** [QcloudApi/qcloudapi-sdk-python#36]
User could not use QcloudApi SDK to use CMQ service, due to missing cmq module.

**Comment by QcloudApi** [comment]
cmq product is not hosted in api platform 2.0, they have individual sdk: https://github.com/tencentyun/cmq-python-sdk/

**Comment by baikai** [comment]
Yes, I see cmq-python-sdk, but...the cmq-python-sdk not support py3
