### ISSUE TITLE
python3 引用QcloudApi失败

### ISSUE THREAD

**Issue by HouPoc** [QcloudApi/qcloudapi-sdk-python#37]
![image](https://user-images.githubusercontent.com/15095470/37239375-4d0a0844-23ef-11e8-9c02-fa0a09eae0cf.png)
在尝试实例代码时，引用QcloudApi 失败

**Comment by HouPoc** [comment]
![image](https://user-images.githubusercontent.com/15095470/37239556-e67d5faa-23f2-11e8-8772-f72dd8986699.png)
请修改文档，或者Class Name

**Comment by HouPoc** [comment]
@QcloudApi

**Comment by QcloudApi** [comment]
qcloudapi3并不是我们维护的。。。我们发布的包是：https://pypi.python.org/pypi/qcloudapi-sdk-python/

**Comment by HouPoc** [comment]
THX
