### ISSUE TITLE
cdb的相关接口功能还没实现吗？

### ISSUE THREAD

**Issue by mds1455975151** [QcloudApi/qcloudapi-sdk-python#39]
cdb模块的GetCdbReadOnlyInstances 操作报6100错误

**Comment by QcloudApi** [comment]
这个错误应该是跟业务具体相关的，sdk这边可能无法处理
不过仍然可以请您贴出完整的错误信息，我们可以代为咨询下业务

**Comment by QcloudApi** [comment]
由于超出两个月仍然没有进一步的信息给出，本问题也确实属于业务范畴和sdk本身无关，故关闭问题单
