### ISSUE TITLE
在windows下貌似有大小写的bug

### ISSUE THREAD

**Issue by raofengyun** [QcloudApi/qcloudapi-sdk-python#41]
Win10 Anaconda 4.5的环境
```bash
pip install qcloudapi-sdk-python
``` 
package安装在：$\Anaconda3\Lib\site-packages\qcloudapi 目录下，但是程序中的package name是大写的QcloudApi，譬如wenzhi.py的
```
from QcloudApi.modules import base
```
这样运行时就会报错：
```bash
  File "$\Anaconda3\lib\site-packages\qcloudapi\modules\wenzhi.py", line 15, in <module>
    from QcloudApi.modules import base
ImportError: No module named 'QcloudApi'
```
我的解决方法是手动把qcloudapi目录名改为了大写的QcloudApi，然后就正常了

**Comment by QcloudApi** [comment]
这个是pip控制的，目前我们对此无能为力。参见https://github.com/pypa/pip/issues/3309

**Comment by raofengyun** [comment]
明白了。我之前运行了
```
pip install qclouapi
```
这个假的package创建了qcloudapi这个目录。  
等后面再运行
```
pip install qcloudapi-sdk-python
```
时，由于Windows不区分大小写，就把这个真的package，也放到上面那个目录中了。  

两个都卸载后，直接```pip install qcloudapi-sdk-python```不会有问题。
