### ISSUE TITLE
什么时候能发布python 3的sdk

### ISSUE THREAD

**Issue by shuhaotech** [QcloudApi/qcloudapi-sdk-python#7]
什么时候能把python 3的sdk，官网介绍的api调用什么的感觉不清晰。。。希望调整一下

**Comment by o0starshine0o** [comment]
强烈要求增加Python3的sdk，什么时候增加了通知我下

**Comment by QcloudApi** [comment]
已经支持python3了。官网的介绍由文档团队负责维护，我们能做的就是在readme中以及示例中更好的介绍用法。
