### ISSUE TITLE
代码能规范下吗？

### ISSUE THREAD

**Issue by aiden0z** [QcloudApi/qcloudapi-sdk-python#9]
1. 需要打包发布，不发布到 pip, 至少应该包含 setup.py 吧？
2. 代码规范能稍微约束下吗？

感觉实在是很难使用啊，能找个懂点 python 的 人来重构下吗？或者至少可以借鉴下 aliyun sdk。

**Comment by QcloudApi** [comment]
已经发布到pypi了，我们已有计划对sdk进行重构。
